module.exports={
    cookieSecret:"This_is_my_first_cookie_object!",
    dbConfig:{
        user:'sa',
        password:'MSSql',
        server:'PPTV3-20181225X\\SQLSERVER2008',
        database:'SupermarketServer'
    },
    user:{
        id:"OKYAKUSAN",
        pwd:"$2b$12$Ew3VurNat.LFFllF3L8AZODZmfGhzxTw8GUy1qfKHrsyJ8uKMZhuy"
    },
    specialUrl:[
        "/login.html",
        "/favicon.ico",
        "/register.html"
    ],
    bcrypt:{
        saltRound:12
    }
}